x-backend: &x-backend
  build:
    context: ..
    dockerfile: docker/backend.Dockerfile
    args:
      USER_ID: ${USER_ID:-1000}
      GROUP_ID: ${GROUP_ID:-1000}
  restart: unless-stopped

services:
  backend:
    <<: *x-backend

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
