services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/healthcheck.json"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    # I forgot why I added that maybe thats not needed anymore with auth (not sure). Maybe thats because I need to communicate to backend:8000 exactly somewhere
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      - backend

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.31.1
    restart: unless-stopped
    ulimits:
      memlock: -1
    command: ["dragonfly", "--cache_mode=true", "--maxmemory=512mb", "--save_schedule=", "--proactor_threads=2"]

  rq-worker:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    depends_on:
      - backend
      - dragonfly
    healthcheck:
      test: ["CMD", "python", "-c", "import redis; r = redis.Redis(host='dragonfly', port=6379); r.ping()"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3
