x-backend: &x-backend
  build:
    context: ..
    dockerfile: docker/backend.Dockerfile
    args:
      USER_ID: ${USER_ID:-1000}
      GROUP_ID: ${GROUP_ID:-1000}
  restart: unless-stopped

services:
  backend:
    <<: *x-backend

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  streaq-worker:
    <<: *x-backend
    depends_on:
      redis:
        condition: service_started
    command: sh -c "uv sync; streaq src.mus.core.streaq_broker.worker"
