services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    volumes:
      - ../frontend:/app
      - node_modules:/app/node_modules
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  node_modules:
