services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../backend/src:/app/src
      - ../data:/app/data
      - ../music:/app/music
    environment:
      - SECRET_KEY=dev_secret_key_please_change_in_production
      - APP_ENV=development
    restart: unless-stopped

  frontend:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
    command: npm run dev -- --host
    depends_on:
      - backend

volumes:
  mus_data:
