services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/healthcheck.json"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    # I forgot why I added that maybe thats not needed anymore with auth (not sure). Maybe thats because I need to communicate to backend:8000 exactly somewhere
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  streaq-worker:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    depends_on:
      - backend
      - redis
    command: sh -c "[ -f /app/requirements.txt ] && uv pip sync /app/requirements.txt; streaq src.mus.core.streaq_broker.worker"
    healthcheck:
      test: ["CMD", "python", "-c", "import redis; r = redis.Redis(host='redis', port=6379); r.ping()"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3
