services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    # I forgot why I added that maybe thats not needed anymore with auth (not sure). Maybe thats because I need to communicate to backend:8000 exactly somewhere
    extra_hosts:
      - "localhost:host-gateway"

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  streaq-worker:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    depends_on:
      redis:
        condition: service_started
    command: sh -c "[ -f /app/requirements.txt ] && uv pip sync /app/requirements.txt; streaq src.mus.core.streaq_broker.worker"
