services:
  mus:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/app:cached
      - mus_data:/app/data
      - /Users/mayurifag/Nextcloud/Music:/music:ro

volumes:
  mus_data:
