---
name: Deploy to Container Registries

"on":
  workflow_run:
    workflows: ["Linters pipeline"]
    types:
      - completed
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  packages: write
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-registries:
    runs-on: ubuntu-latest
    # Only run if the linters workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to get the commit message
      - name: Set lowercase repository name
        run: |
          echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
      - name: Set build metadata
        id: build_meta
        run: |
          echo "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "commit_title=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
      - name: Build and push to both registries
        uses: docker/build-push-action@v6
        with:
          file: docker/production/production.Dockerfile
          push: true
          build-args: |
            COMMIT_TITLE=${{ steps.build_meta.outputs.commit_title }}
            COMMIT_SHA=${{ github.sha }}
            BUILD_DATE=${{ steps.build_meta.outputs.build_date }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}
            ghcr.io/${{ env.REPO_LOWER }}:latest
            ghcr.io/${{ env.REPO_LOWER }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Trigger watchtower
        env:
          WATCHTOWER_TOKEN: ${{ secrets.WATCHTOWER_HTTP_API_TOKEN }}
          WATCHTOWER_URL: ${{ secrets.WATCHTOWER_URL }}
        run: |
          curl -H "Authorization: Bearer $WATCHTOWER_TOKEN" $WATCHTOWER_URL
